defmodule Once.PgTest do
  use TestOnce.DataCase, async: true

  alias MyApp.{PgRepo, Schema}
  import Ecto.Query

  defp get_raw() do
    from(r in "test_table",
      select: [:autogenerated, :bin_id, :bigint_id, :string_id]
    )
  end

  defp get_raw(field, value), do: get_raw() |> by_field(field, value)

  defp get(field, value) do
    from(r in Schema) |> by_field(field, value)
  end

  defp by_field(query, field, value), do: where(query, [a], field(a, ^field) == ^value)

  describe "autogenerated" do
    test "can be autogenerated" do
      assert {:ok, inserted} = Schema.changeset(%{}) |> PgRepo.insert()
      assert <<_::88>> = inserted.autogenerated
      res = get_raw() |> PgRepo.one()
      assert is_integer(res.autogenerated)
    end
  end

  describe "bigint type" do
    test "correctly returns input" do
      for {input, expected, expected_raw} <- [
            {0, "AAAAAAAAAAA", 0},
            {@signed_min, "gAAAAAAAAAA", @signed_min},
            {@signed_max, "f_________8", @signed_max},
            {@unsigned_max, "__________8", -1}
          ] do
        assert {:ok, inserted} = Schema.changeset(%{bigint_id: input}) |> PgRepo.insert()
        assert expected == inserted.bigint_id
        assert %{} = get_raw(:bigint_id, expected_raw) |> PgRepo.one()
        assert %{bigint_id: ^expected} = get(:bigint_id, input) |> PgRepo.one()
      end
    end
  end

  describe "bin type" do
    test "correctly returns input" do
      for {input, expected, expected_raw} <- [
            {0, "AAAAAAAAAAA", <<0, 0, 0, 0, 0, 0, 0, 0>>},
            {@signed_min, "gAAAAAAAAAA", <<128, 0, 0, 0, 0, 0, 0, 0>>},
            {@signed_max, "f_________8", <<127, 255, 255, 255, 255, 255, 255, 255>>},
            {@unsigned_max, "__________8", <<255, 255, 255, 255, 255, 255, 255, 255>>}
          ] do
        assert {:ok, inserted} = Schema.changeset(%{bin_id: input}) |> PgRepo.insert()
        assert expected == inserted.bin_id
        assert %{} = get_raw(:bin_id, expected_raw) |> PgRepo.one()
        assert %{bin_id: ^expected} = get(:bin_id, input) |> PgRepo.one()
      end
    end
  end

  describe "string type" do
    test "correctly returns input" do
      for {input, expected, expected_raw} <- [
            {0, "AAAAAAAAAAA", "AAAAAAAAAAA"},
            {@signed_min, "gAAAAAAAAAA", "gAAAAAAAAAA"},
            {@signed_max, "f_________8", "f_________8"},
            {@unsigned_max, "__________8", "__________8"}
          ] do
        assert {:ok, inserted} = Schema.changeset(%{string_id: input}) |> PgRepo.insert()
        assert expected == inserted.string_id
        assert %{} = get_raw(:string_id, expected_raw) |> PgRepo.one()
        assert %{string_id: ^expected} = get(:string_id, input) |> PgRepo.one()
      end
    end
  end
end
