defmodule MyApp.MysqlRepo.Migrations.First do
  use Ecto.Migration

  def change do
    create table("test_table") do
      add(:autogenerated, :bigint)
      add(:bin_id, :binary)
      add(:bigint_id, :bigint)
      add(:string_id, :string)
      add(:unsigned_id, :"bigint unsigned")
    end
  end
end
