defmodule MyApp.PrefixSchema do
  use Ecto.Schema
  import Ecto.Changeset
  alias Once.Prefixed

  schema "test_table" do
    field :autogenerated, Prefixed, prefix: "t_", autogenerate: true

    field :bigint_id, Prefixed, prefix: "t_", ex_format: :signed

    field :bin_id, Prefixed, prefix: "t_", db_format: :raw
    field :string_id, Prefixed, prefix: "t_", persist_prefix: true, db_format: :url64

    # mysql-only
    field :unsigned_id, Prefixed, prefix: "t_", db_format: :unsigned, load_in_query: false
  end

  def changeset(struct_or_cs \\ %__MODULE__{}, params) do
    struct_or_cs |> cast(params, [:bin_id, :bigint_id, :string_id, :unsigned_id])
  end
end
