defmodule MyApp.Schema do
  use Ecto.Schema
  import Ecto.Changeset

  schema "test_table" do
    field :autogenerated, NoNoncenseID, autogenerate: true

    field :bigint_id, NoNoncenseID

    field :bin_id, NoNoncenseID, db_format: :raw
    field :string_id, NoNoncenseID, db_format: :encoded

    # mysql-only
    field :unsigned_id, NoNoncenseID, db_format: :unsigned, load_in_query: false
  end

  def changeset(struct_or_cs \\ %__MODULE__{}, params) do
    struct_or_cs |> cast(params, [:bin_id, :bigint_id, :string_id, :unsigned_id])
  end
end
